### ISSUE TITLE
Perhaps a better default in cups-browsed.conf

### ISSUE THREAD

**Issue by ramones79** [OpenPrinting/cups-browsed#38]
**Describe the bug**
In the light of the recently discovered vulnerability in cups-browsed, I'm looking at the cups-browsed config file (cups-browsed.conf) and don't understand why the default is not to limit the network access only to the local network, since this will be sufficient for users in 99% of the times, and the 1% that will actually try to connect from remote location should manually set their networking permissions (allowances).
It makes more sense to me - what do you say, guys?

**To Reproduce**
1. Open cups-browsed config file (/etc/cups/cups-browsed.conf)
2. Find the commented (disabled) line 
`# BrowseAllow 192.168.1.0/24`

**Expected behavior**
Better this line to be uncommented (enabled) by default as a more sensible default:
`BrowseAllow 192.168.1.0/24`

**Additional context**
It is my understanding, that uncommenting this line, and according to the in-file explanation, it will enable ONLY access to the cups-browsed from the local network (192.168.1.0/24) and will deny access to any other IP - correct ?

Thank you.

**Comment by michaelrsweet** [comment]
We are planning on removing CUPS browse support entirely since it hasn't been used since CUPS 1.4 and the security and performance issues the protocol has are not fixable.

Regarding the default, back in the CUPS 1.4 and earlier days we did indeed use a "BrowseAllow @LOCAL" configuration which mapped to the local IPv4 subnet(s) for the host. However, cups-browsed does not support @LOCAL and 192.168.1.0/24 is one of many common subnets you'll find on home and office networks - *If* we were to continue support for CUPS browsing, we'd want to add @LOCAL support.

Thank you for the bug report.
